React Group Project: Space Travelers Hub
Tadessejemal1/React-Group-Project pull request #40
Opened 2022-09-28 21:22 UTC by LokurasRlz

# In this branch, We have worked on the following things: 

- Built a web application for a company that provides commercial and scientific space travel services. ✔️ 
- Setup Linters. ✔️
- Followed Linters. ✔️
- Followed GitFlow. ✔️
- Used Ducks Pattern.
- Used React components.. ✔️
- Used React props. ✔️
- Used React Router. ✔️
- Connected React and Redux. ✔️
- Handled events in a React app. ✔️
-  React state was used. ✔️
- Unit tests with React Testing Library were created. ✔️
-  Styles in a React app were used. ✔️
-  Used React life cycle methods. ✔️
- Applied React best practices and language style guides in code. ✔️
- Store, actions, and reducers were used in React.  ✔️
-  React state was used. ✔️
- Code reviews for team members were performed. ✔️
- Webpage Deployed. ✔️

2022-09-28 21:24 UTC, LokurasRlz commented
We don't know how to stop de bot from Netlify. We tried to use it but It didn't work for us.

2022-09-28 23:56 UTC, FrederickMih requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights

- Pull Request has a good title and summary :+1: 
- Correct GitHub workflow has been followed :heavy_check_mark: 
- Rockets and Missions pages have been implemented :+1: 
- No Linter error :heavy_check_mark: 

## Required Changes ♻️

- [ ] Let's try to fix these console errors:

![Screenshot from 2022-09-29 00-41-22](https://user-images.githubusercontent.com/63087491/192908255-0cec723b-2469-473b-8fe8-af982e4b66ca.png)

- [ ] Let's kindly fix the deployment errors before submitting our project again.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-28 23:56 UTC, FrederickMih commented on src/components/Rockets/rockets.js
> +      console.log('reserved...', rockets);
- [ ] Please do not commit console.log to your repo. It really kills performance and can make confidential data to be visible to anyone using the browser tools to look at your website.

![Screenshot from 2022-09-29 00-01-23](https://user-images.githubusercontent.com/63087491/192903415-2d38a78c-1aba-4166-9b6c-1182326c1ae4.png)

It's ugly.

kindly remove all console.log lines in your codebase.

2022-09-29 16:21 UTC, KayLemba approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello  @LokurasRlz @Tadessejemal1       , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- Your project is professional 
- Your repo is professional 
- Well structured files 
- No linter errors 
- Nice UI design


Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-29 17:35 UTC, merged